#!/bin/python3

import math
import os
import random
import re
import sys

def timeConversion(s):
    hour = int(s[:2])
    modifier = s[-2:]
    rest_time = s[2:-2] 

    if modifier == 'AM':
        if hour == 12:
            hour = 0
    else:  # PM
        if hour != 12:
            hour += 12

    return f"{hour:02d}{rest_time}"

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()
    result = timeConversion(s)

    fptr.write(result + '\n')
    fptr.close()
